language: python
python:
  - "3.5"
sudo: required
dist: trusty
services:
  - redis-server
cache:
  directories:
    - $GDALINST
    - ~/.cache/pip
env:
  global:
    - OTHER_PY_PACKAGES=$HOME/py_tmp
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
before_install:
  - ./misc/install_gdal.sh
  - export PATH=$GDALINST/gdal-2.1.2/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-2.1.2/lib:$LD_LIBRARY_PATH
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
  - npm -g install topojson
  - pip install --upgrade "setuptools>=25.1" pip
  - pip install -r requirements-dev.txt
  - python setup.py install
# before_script:
#   - magrit -p 9999
#   - sleep 10
script:
  - magrit --help
  - py.test tests/test.py -p no:flaky
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - libpython3.5-dev
      - libopenblas-base
      - libopenblas-dev
      - gdal-bin
      - libuv-dev
      - libgdal-dev
      - libproj-dev
      - libspatialindex-dev
      - libfreetype6
      - libfreetype6-dev
      - libv8-3.14-dev
      - libffi-dev
      - redis-server
      - nodejs
      - nodejs-dev
      - node-gyp
      - npm
      - libxslt1-dev
      - libxml2
      - libxml2-dev
      - libkml-dev
