language: python
python:
  - "3.5"
sudo: required
dist: trusty
services:
  - redis-server
cache:
  directories:
    - $GDALINST
    - $PHANTOMJSDIR
    - ~/.cache/pip
env:
  global:
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
    - PHANTOMJSDIR=$HOME/phantomjs
before_install:
  - ./misc/install_gdal.sh
  - ./misc/install_phantomjs.sh
  - export PATH=$GDALINST/gdal-2.1.0/bin:$PHANTOMJSDIR/phantomjs-2.1.1-linux-x86_64/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-2.1.0/lib:$LD_LIBRARY_PATH
install:
  - npm -g install topojson
  - pip install --upgrade "setuptools>=25.1" pip
  - pip install -r requirements-dev.txt
  - python setup.py install
script:
  - noname_app --help
  - py.test tests/test.py
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - libpython3.5-dev
      - libopenblas-base
      - gdal-bin
      - libgdal-dev
      - libproj-dev
      - libv8-3.14-dev
      - libffi-dev
      - r-base
      - redis-server
      - nodejs
      - nodejs-dev
      - node-gyp
      - npm
      - libfftw3-dev
      - libzmq3-dev
